controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Patients;
use app\models\Genres;
use app\models\Wilayas;
use app\models\Visites;
use app\models\PatientsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\web\Response;
use kartik\mpdf\Pdf;


/**
 * SiteController implements the CRUD actions for Patients model.
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function init()
    {
      \Yii::$app->language = 'fr_FR';
      Parent::init();
    }
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Patients models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PatientsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,['wilaya']);
        //dd($dataProvider->getModels());
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    public function actionIndexAjax()
    {
      $searchModel = new PatientsSearch();
      $dataProvider = $searchModel->search(Yii::$app->request->queryParams,['wilaya']);
      //dd($dataProvider->getModels());
      return $this->renderAjax('index', [
          'searchModel' => $searchModel,
          'dataProvider' => $dataProvider,
      ]);
    }



    public function actionDatatables()
    {
        return [
             'datatables' => [
                 'class' => 'nullref\datatable\DataTableAction',
                 'query' => Patients::find()->with('wilaya'),
                 'applyOrder' => function($query, $columns, $order) {
                    //custom ordering logic
                    return $query;
                 },
                 'applyFilter' => function($query, $columns, $search) {
                    //custom search logic
                    return $query;
                 },
             ],
        ];
    }
    /**
     * Displays a single Patients model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $visites= Visites::find()->where(['patient_id' => $id])->orderBy('id DESC')->all();
        $model=$this->findModel($id);

        $age= date_diff(date_create($model->naissance), date_create('today'))->y;

        return $this->render('view', [
            'model' => $model,
            'visites'=> $visites,
            'age'=>$age,
        ]);
    }
    public function actionViewAjax($id)
    {
        $visites= Visites::find()->where(['patient_id' => $id])->orderBy('id DESC')->all();
        $model=$this->findModel($id);
        $age= date_diff(date_create($model->naissance), date_create('today'))->y;
        //dd($visites);
        return $this->renderAjax('view', [
            'model' => $model,
            'visites'=> $visites,
            'age'=>$age,
        ]);
    }

    public function actionOrdonnance($id) {

    $visite= Visites::find()->with('patient')->where(['id'=>$id])->one();
    //dd($visite);
    //$traitement=  Yii::$app->request->post('traitement');
    // get your HTML raw content without any layouts or scripts
    $content = $this->renderPartial('_ordonnance',['visite'=>$visite]);

    // setup kartik\mpdf\Pdf component
    $pdf = new Pdf([
        // set to use core fonts only
        'mode' => Pdf::MODE_UTF8,
        // A4 paper format
        'format' => [148,210],//Pdf::FORMAT_LEGAL,
        // portrait orientation
        'orientation' => Pdf::ORIENT_PORTRAIT,
        // stream to browser inline
        'destination' => Pdf::DEST_BROWSER,
        // your html content input
        'content' => $content,
        // format content from your own css file if needed or use the
        // enhanced bootstrap css built by Krajee for mPDF formatting
        'cssFile' => '@vendor/bower/bootstrap/dist/css/bootstrap.min.css',
        // any css to be embedded if required
        'cssInline' => '.mrg{margin-right:50px;} div{font-size:15px; display:inline-block; } .bld{font-weight:bold}',
         // set mPDF properties on the fly
        'options' => ['title' => 'ordonnancelogiciel swiftmed'],
         // call mPDF methods on the fly
        'methods' => [
            'SetFooter'=>['générée par le logiciel swiftmed '],
            //'SetFooter'=>['{PAGENO}'],
        ]
    ]);

        // return the pdf output as per the destination setting
        return $pdf->render();
    }

    protected function frdatetosql($date)
    {
      //convert frenhc date to date
     $find = array('janvier', 'février', 'mars', 'avril', 'mai', 'juin', 'juillet', 'août', 'septembre', 'octobre', 'novembre', 'décembre');
     $replace = array('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December');
     $date = str_replace($find, $replace, strtolower($date));
     $date = date('Y/m/d', strtotime($date));

     return $date;
    }
    public function actionNextVisit()
    {
      if(Yii::$app->request->isAjax)
      {
        $post=Yii::$app->request->Post();
        $patient=Patients::findOne($post['id']);



        //var_dump(date_parse($arr));
        //var_dump(date_parse());

        $patient->next_visit=$this->frdatetosql($post['date']);
        if($patient->save())
        {
          return 'true';
        }else return 'false';
      }
    }
    /**
     * Creates a new Patients model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Patients();

        $genders = ArrayHelper::map(Genres::find()->all(), 'id', 'nom');
        $Wilayas = ArrayHelper::map(Wilayas::find()->all(), 'code', 'nom');
        $post=Yii::$app->request->post();
        //var_dump($post);die();
        //dd($post);
        if($post)$post['Patients']['naissance']=$this->frdatetosql($post['Patients']['naissance']);
        if ($model->load($post) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
            //return $this->runAction('view-ajax',['id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'genres' => $genders,
                'wilayas' => $Wilayas
            ]);
        }
    }
    public function actionCreateAjax()
    {
        $model = new Patients();

        $genders = ArrayHelper::map(Genres::find()->all(), 'id', 'nom');
        $Wilayas = ArrayHelper::map(Wilayas::find()->all(), 'code', 'nom');
        $post=Yii::$app->request->post();
        //var_dump($post);die();
        //dd($post);


        if($post)$post['Patients']['naissance']=$this->frdatetosql($post['Patients']['naissance']);
        if ($model->load($post) && $model->save()) {
            //return $this->renderAjax('view', ['id' => $model->id]);
            return $this->runAction('view-ajax',['id' => $model->id]);

        } else {
            return $this->renderAjax('create', [
                'model' => $model,
                'genres' => $genders,
                'wilayas' => $Wilayas
            ]);
        }
    }

    /**
     * Updates an existing Patients model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $genders = ArrayHelper::map(Genres::find()->all(), 'id', 'nom');
        $Wilayas = ArrayHelper::map(Wilayas::find()->all(), 'code', 'nom');
        $post=Yii::$app->request->post();
        if($post)$post['Patients']['naissance']=$this->frdatetosql($post['Patients']['naissance']);

        if ($model->load($post) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'genres' => $genders,
                'wilayas' => $Wilayas
            ]);
        }
    }
    public function actionUpdateAjax($id)
    {
        $model = $this->findModel($id);
        $genders = ArrayHelper::map(Genres::find()->all(), 'id', 'nom');
        $Wilayas = ArrayHelper::map(Wilayas::find()->all(), 'code', 'nom');
        $post=Yii::$app->request->post();
        if($post)$post['Patients']['naissance']=$this->frdatetosql($post['Patients']['naissance']);

        if ($model->load($post) && $model->save()) {
          return $this->runAction('view-ajax',['id' => $model->id]);
        } else {
            return $this->renderAjax('update', [
                'model' => $model,
                'genres' => $genders,
                'wilayas' => $Wilayas
            ]);
        }
    }

    /**
     * Deletes an existing Patients model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Patients model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Patients the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Patients::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/site/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;


/* @var $this yii\web\View */
/* @var $model app\models\Patients */
/* @var $form yii\widgets\ActiveForm */
?>
<hr>

<div class="patients-form collapse">

     <?php $form = ActiveForm::begin(/*['action'=> $model->isNewRecord ? '/site/create' : '/site/update']*/); ?>

    <?= $form->field($model, 'nom',['options'=>['class'=>'col-md-3']])->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'prenom',['options'=>['class'=>'col-md-3']])->textInput(['maxlength' => true]) ?>

    <?php /* $form->field($model, 'naissance',['options'=>['class'=>'col-md-6']])->textInput() */?>

    <?= $form->field($model,'naissance',['options'=>['class'=>'col-md-3']])->widget(yii\jui\DatePicker::className(),['language'=>'fr_FR','dateFormat' => 'long','clientOptions' => ['changeYear'=> 'true','changeMonth' => 'true','yearRange' => '1900:2099'],'options'=>['class'=>'form-control']]) ?>

    <?= $form->field($model, 'genre',['options'=>['class'=>'col-md-3']])->dropDownlist($genres,['prompt'=>'-']) ?>

    <?= $form->field($model, 'tel',['options'=>['class'=>'col-md-6']])->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'profession',['options'=>['class'=>'col-md-6']])->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'ville',['options'=>['class'=>'col-md-6']])->dropDownlist($wilayas,['prompt'=>'-']) ?>

    <?= $form->field($model, 'adresse',['options'=>['class'=>'col-md-6']])->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'antecedents_per',['options'=>['class'=>'col-md-6']])->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'antecedents_fam',['options'=>['class'=>'col-md-6']])->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description',['options'=>['class'=>'col-md-6']])->textInput(['maxlength' => true]) ?>

    <div class="form-group   pull-right">
      <br>
        <?= Html::submitButton($model->isNewRecord ? 'Créer' : 'Modifier', ['class' => $model->isNewRecord ? 'btn btn-success ajax-request-form' : 'btn btn-primary ajax-request-form','href' => $model->isNewRecord ? '/site/create-ajax' : '/site/update-ajax?id='.$model->id]) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/site/_ordonnance.php
<div align="center">  < Informations cabinet médical > </div>
<hr>
<div    align="right"><span class="bld">Le : </span><span><?= $visite->date_visite ?></span></div>

<div style="font-family:helvetica nue;">
<span class="bld">Nom : </span><span class="mrg"><?= $visite->patient->nom ?></span><br>
<span class="bld">   Prénom : </span><span class="mrg"><?= $visite->patient->prenom ?></span>
<div align="rright"> <span class="bld"  >   Age : </span><span class="mrg"><?=  date_diff(date_create($visite->patient->naissance), date_create('today'))->y ?></span></div>
</div>
<br>
<br>
<h4 align="center">ORDONNANCE</h4>
<br>
<br>
<br>
<br>
<div align="center"><?= $visite->prescription ?></div>

views/site/_patient_info.php
    <?php

      echo '<div class="container-fluid"><div class="col-md-3"><label>Identifiant: </label><br>
      <label>Genre: </label>
      </div>';

      echo '<div class="info col-md-3">
        <span id="id-patient">'.$model->id.'</span><br>
        <span>'.$model->sex->nom.' ( '.$age.' )</span><br></div>';

      echo '<div class="col-md-3">
        <label>Nom: </label><br>
        <label>Prénom: </label><br>
        </div>';

        echo '<div class="info col-md-3">
          <span>'.$model->nom.'</span><br>
          <span>'.$model->prenom.'</span><br></div></div>';

      echo ' <div class="row pull-right" data-toggle="collapse" data-target="#more"><span class="drop-menu text-primary">Voir plus</span></div>
            <br>
            <div id="more" class=" collapse">';

      echo '<br><div class="container-fluid "><div class="col-md-3">
      <label>Tel: </label><br>

      </div>';

      echo '<div class="info col-md-3">
        <span>'.$model->tel.'</span><br>
        </div>';

        echo '<div class="col-md-3">
        <label>Profession: </label><br>

        </div>';

      echo '<div class="info col-md-3">
        <span>'.$model->profession.'</span><br></div>

        </div>';

      echo '<br><div class="container-fluid "><div class="col-md-3">
      <label>Ville: </label><br>

      </div>';

      echo '<div class="info col-md-3">
        <span>'.$model->wilaya->nom.'</span><br>
         </div>';



        echo '<div class="col-md-3">
        <label>Adresse: </label><br>

        </div>';
      echo '<div class="info col-md-3">
        <span>'.$model->adresse.'</span><br></div>
        </div>';

        echo '<br><div class="container-fluid "><div class="col-md-3">
        <label>Antécedents personnels:</label><br>

        </div>';

        echo '<div class="info col-md-3">
          <span>'.$model->antecedents_per.'</span><br>
           </div> ';

        echo ' <div class="col-md-3">
         <label>Antécedents familiaux: </label><br>

        </div>';

        echo '<div class="info col-md-3">
           <span>'.$model->antecedents_fam.'</span><br>
          </div></div>';

        echo '<br><div class="container-fluid "><div class="col-md-3">
        <label>Note: </label><br>

        </div>';
      echo '<div class="info col-md-9">
        <span>'.$model->description.'</span><br>
        </div></div>
        </div>';

     ?>



 

views/site/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\PatientsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="patients-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'nom') ?>

    <?= $form->field($model, 'prenom') ?>

    <?= $form->field($model, 'naissance') ?>

    <?= $form->field($model, 'genre') ?>

    <?php // echo $form->field($model, 'adresse') ?>

    <?php // echo $form->field($model, 'ville') ?>

    <?php // echo $form->field($model, 'tel') ?>

    <?php // echo $form->field($model, 'description') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/site/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Patients */

$this->title = 'Nouveau Patient';
$this->params['breadcrumbs'][] = ['label' => 'Patients', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="patients-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'genres' => $genres,
        'wilayas' => $wilayas
    ]) ?>

</div>

views/site/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
/* @var $this yii\web\View */
/* @var $searchModel app\models\PatientsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Liste des Patients';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class=" collapse patients-index">

    <h1 class="row "><?= Html::encode($this->title) ?> </h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
<!--
    <p class="col-md-2 pull-right">
        <?= Html::a('Nouveau Patient', ['/site/create-ajax'], ['class' => 'ajax-request btn btn-success']) ?>
    </p>-->



<?= \nullref\datatable\DataTable::widget([
    'data' => $dataProvider->getModels(),
    'id'=>'datatable-id',
    /*'serverSide' => true,
    'ajax' => '/site/index-json',*/
    'language'=>["sProcessing"=>"Traitement en cours ...",
    "sLengthMenu"=>"Afficher _MENU_ lignes",
    "sZeroRecords"=>"Aucun résultat trouvé",
    "sEmptyTable"=>"Aucune donnée disponible",
    "sInfo"=>"Lignes _START_ à _END_ sur _TOTAL_",
    "sInfoEmpty"=>"Aucune ligne affichée",
    "sInfoFiltered"=>"(Filtrer un maximum de_MAX_)",
    "sInfoPostFix"=>"",
    "sSearch"=>"Chercher:",
    "sUrl"=>"",
    "sInfoThousands"=>",",
    "sLoadingRecords"=>"Chargement...",
    "oPaginate"=>[
      "sFirst"=>"Premier", "sLast"=>"Dernier", "sNext"=>"Suivant", "sPrevious"=>"Précédent"
    ],
    "oAria"=>[
      "sSortAscending"=>": Trier par ordre croissant", "sSortDescending"=>": Trier par ordre décroissant"
    ]],
    'width' =>'900px',
    'columns' => [
        'id',
        'nom',
        'prenom',
        'naissance',
        'ville',

        [
            'class' => 'nullref\datatable\LinkColumn',
            'url' => ['/view-ajax'],
            'options' => [   'class'=>'ajax-request'],
            'queryParams' => ['id'],
            'label' => 'Inspecter <i class="glyphicon glyphicon-search"></i>',
        ],
    ],
]) ?>


</div>

<?php

$session=Yii::$app->session;
$session->open();
if(!$session->get('new'))
{$session->set('new', 'true');
 ?>

<div id="welcome" class="collapse"><div><h1 class="collapse">Bienvenue dans <img src="images/logo.png" /> </h1><h2 class="collapse">Votre système de gestion des Patients.</h2><p class="sponsor"> Sponsorisé par <br><br><img  src="/images/sponsor.png" /></p></div></div>

<?php
}
?>

views/site/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Patients */

$this->title = 'Modifier Patient n°: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Patients', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="patients-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'genres'=>$genres,
        'wilayas'=>$wilayas,
    ]) ?>

</div>

views/site/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Patients */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Patients', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
$formatter = \Yii::$app->formatter;
//dd($visites[0]->explo);

?>

<div class="col-md-3">
<h3>Historique du Patient</h3>
<div  id="historique">
<ul>
<?php

  foreach ($visites as $key => $value) {
    echo '<li class="visite '.(($key=='0')?'selected':$key).'" data-value="'.$value->id.'">'.$formatter->asDate($value->date_visite,'long')."</li>";
  }

 ?>
</ul>
</div>
</div>
<div class="patients-view col-md-9 collapse">


    <div class="row">
    <p class="col-md-5">
        <?= Html::a('Modifier les informations du patient', ['update-ajax', 'id' => $model->id], ['class' => 'btn btn-primary ajax-request']) ?>
        <?php /* Html::a('Supprimer', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'êtes vous sûr de vouloir supprimer ce Patient?',
                'method' => 'post',
            ],
        ]) */?>
    </p>
    <p class="text-primary col-md-4">
      Prochaine visite programmée pour le :
    </p>
    <p class="next-visit-container col-md-3">
    <?= yii\jui\DatePicker::widget(['name' => 'next_visit','value' => ($model->next_visit)?$model->next_visit:'','language'=>'fr_FR','dateFormat' => 'long','id'=>'next-visit']) ?>
    <br><span id="saved" class="text-success">&nbsp</span>
    </p>
  </div>
    <hr>

    <?= $this->render('_patient_info',['model'=>$model,'age'=>$age]) ?>

     <hr>
     <div class="container-fluid">
       <h4  >
         <span class="visite_heading" >Date de la dernière visite:</span>
          &nbsp <label id="date-visite" class="text-success"> &nbsp
            <?php  echo isset($visites[0])? $formatter->asDate($visites[0]->date_visite,'long'):' - Historique du patient vide.'; ?>
          </label>
          <!--<a id="print-link" target="_blank" href="ordonnance?id=<?php if(isset($visites[0])) echo ($visites[0]['id']) ; ?>" <?php if(!isset($visites['0'])) { echo 'class="collapse"'; } ?> ><i class=" print pull-right glyphicon glyphicon-print"></i>
          </a>-->
        </h4>
        <button id="new-visit" class="btn btn-primary pull-right">Nouvelle visite</button>
       </div>
       <?php if(isset($visites['0'])) { ?>

         <?= $this->render('_visit_record',['visites'=>$visites]) ?>


        <?php }else{ ?>

          <?= $this->render('_visit_blank') ?>

        <?php } ?>


        <?= $this->render('_new_visit_container') ?>

      <!-- visit form -->
      <p class="sponsor-visite"> Sponsorisé par <br><br><img  src="/images/sponsor.png" /></p>

</div>